[package]
name = "gb-r"
version = "0.1.0"
authors = ["Davide Davelli <develop.bs2@gexcel.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
 byteorder = "1.3.4"  