[package]
name = "gb-r"
version = "0.1.0"
authors = ["Davide Davelli <develop.bs2@gexcel.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
 byteorder = "1.3.4"  
 cursive = "0.15.0"
 cursive-tabs = "^0"
 cursive-flexi-logger-view = "^0"
 enum_primitive = "*"
 flexi_logger = "0.15.1"
 log = "0.4.8"
 num = "0.3.1"

