[package]
name = "gb-r"
version = "0.1.0"
authors = ["Davide Davelli"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
 beryllium = { version = "0.3.2", default-features = false, features = ["extern_crate_raw_window_handle", "static_link"] }
 byteorder = "1.3.4"  
 cursive = { version = "0.17.0", default-features = false, features = ["crossterm-backend"]}
 cursive_buffered_backend = "0.6"
 cursive-tabs = "0.7"
 cursive-flexi-logger-view = "0.5"
 enum_primitive = "*"
 flexi_logger = "0.22"
 log = "0.4.8"
 num = "0.3.1"
 pixels = "0.2.0"

